import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ClientSessionProvider } from "@/app/_components/client-session-provider";
import { GlobalToastHandler } from "@/app/_components/global-toast-handler";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ClientSessionProvider>
          <TRPCReactProvider>
            <GlobalToastHandler />
            {children}
            <Toaster />
          </TRPCReactProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
